// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vvyosmthkkoemdizfuep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2eW9zbXRoa2tvZW1kaXpmdWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Nzc4MDksImV4cCI6MjA3MjM1MzgwOX0.2J_fftyV9S6hJTd02fItK2rt9_zkQAdtt2exMW8yD4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);